export const INIT = 'INIT';
export const MODERATOR_CONNECTED = 'MODERATOR_CONNECTED';
export const PLAYER_REGISTRATION = 'PLAYER_REGISTRATION';
export const WAITING_FOR_ROUND_START = 'WAITING_FOR_ROUND_START';
export const ROUND_IN_PROGRESS = 'ROUND_IN_PROGRESS';
export const RESULTS = 'RESULTS';
export const END = 'END';
